language: node_js
node_js:
  - stable
script:
  - npm run test
  - npm run build
deploy:
  target-branch: gh-pages
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: build
  on:
    all_branches: true
