language: node_js
node_js:
  - "10.11.0"

script:
  - npm run test
  - npm run build

deploy:
  target-branch: gh-pages
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  on:
    branch: master
